### Neuen Benutzer registrieren
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "username": "bruceWayne",
  "firstName": "Bruce",
  "lastName": "Wayne",
  "birthDate": "1993-03-02",
  "email": "bruce.wayne@example.com",
  "password": "securePassword123"
}

> {%
    client.test("Status ist 201", function() {
        client.assert(response.status === 201, "Erwartet: 201, Erhalten: " + response.status);
    });
%}

### Benutzer einloggen (Falscher Login)
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username": "bruceWayne",
  "password": "falschesPasswort123"
}

> {%
    client.test("Status ist 401", function() {
        client.assert(response.status === 401, "Erwartet: 401, Erhalten: " + response.status);
    });
%}


### Benutzer einloggen
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username": "bruceWayne",
  "password": "securePassword123"
}

> {%
    client.test("Status ist 200", function() {
        client.assert(response.status === 200, "Erwartet: 200, Erhalten: " + response.status);
    });

    client.test("Token vorhanden", function() {
        client.assert(response.body.token !== undefined, "Kein Token in Response");
    });

    // Token global speichern
    client.global.set("authToken", response.body.token);
    client.log("Token gespeichert: " + response.body.token);
%}

### Benutzer löschen
DELETE http://localhost:8000/api/v1/auth
Authorization: Bearer {{authToken}}
Content-Type: application/json

> {%
    client.test("Status ist 204", function() {
        client.assert(response.status === 204, "Erwartet: 204, Erhalten: " + response.status);
    });

%}
